// Code generated by MockGen. DO NOT EDIT.
// Source: sysmon/internal/activity/port (interfaces: Pointer)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_pointer.go -package=mock sysmon/internal/activity/port Pointer
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPointer is a mock of Pointer interface.
type MockPointer struct {
	ctrl     *gomock.Controller
	recorder *MockPointerMockRecorder
	isgomock struct{}
}

// MockPointerMockRecorder is the mock recorder for MockPointer.
type MockPointerMockRecorder struct {
	mock *MockPointer
}

// NewMockPointer creates a new mock instance.
func NewMockPointer(ctrl *gomock.Controller) *MockPointer {
	mock := &MockPointer{ctrl: ctrl}
	mock.recorder = &MockPointerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPointer) EXPECT() *MockPointerMockRecorder {
	return m.recorder
}

// Bounds mocks base method.
func (m *MockPointer) Bounds() (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bounds")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Bounds indicates an expected call of Bounds.
func (mr *MockPointerMockRecorder) Bounds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bounds", reflect.TypeOf((*MockPointer)(nil).Bounds))
}

// MoveTo mocks base method.
func (m *MockPointer) MoveTo(x, y int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveTo", x, y)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveTo indicates an expected call of MoveTo.
func (mr *MockPointerMockRecorder) MoveTo(x, y any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveTo", reflect.TypeOf((*MockPointer)(nil).MoveTo), x, y)
}

// Position mocks base method.
func (m *MockPointer) Position() (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Position")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Position indicates an expected call of Position.
func (mr *MockPointerMockRecorder) Position() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Position", reflect.TypeOf((*MockPointer)(nil).Position))
}
