// Code generated by MockGen. DO NOT EDIT.
// Source: sysmon/internal/activity/port (interfaces: Pointer)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_pointer.go -package=mock sysmon/internal/activity/port Pointer
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPointer is a mock of Pointer interface.
type MockPointer struct {
	ctrl     *gomock.Controller
	recorder *MockPointerMockRecorder
	isgomock struct{}
}

// MockPointerMockRecorder is the mock recorder for MockPointer.
type MockPointerMockRecorder struct {
	mock *MockPointer
}

// NewMockPointer creates a new mock instance.
func NewMockPointer(ctrl *gomock.Controller) *MockPointer {
	mock := &MockPointer{ctrl: ctrl}
	mock.recorder = &MockPointerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPointer) EXPECT() *MockPointerMockRecorder {
	return m.recorder
}

// Nudge mocks base method.
func (m *MockPointer) Nudge(dx, dy int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nudge", dx, dy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Nudge indicates an expected call of Nudge.
func (mr *MockPointerMockRecorder) Nudge(dx, dy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nudge", reflect.TypeOf((*MockPointer)(nil).Nudge), dx, dy)
}
